version: "3"

services:
  app:
    build:
      context: ./app
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 3000 --reload
    container_name: app
    networks:
      - backend-network
    tty: true
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"

networks:
  backend-network:
    driver: bridge
